mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''

cfw-profile-mixin:
  dns:
    enable: true
    listen: :53
    enhance-mode: fake-ip
    nameserver:
      - 192.168.10.2
  experimental:
    interface-name: ethernet

# Will be ignored after profile selection
proxies:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
rules:
  - 'MATCH,DIRECT'
